apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-service
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        role: master
        tier: backend
    spec:
      containers:
      - name: api
        image: korobokvk/reporty-client-service-api:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3030